### ISSUE TITLE
connect.session() MemoryStore is not designed for a production environment

### ISSUE THREAD

**Issue by aneesh-neelam** [floatdrop/express-mongo-db#5]
"Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process."

I get this whenever I run it with NODE_ENV=production. I use a single instance only, however does it leak memory? I've observed RAM usage for around 12 hours courtesy of New Relic and it does seem to be using more memory. 

Could this be fixed?

**Comment by floatdrop** [comment]
Do not use `connect.session` with memory storage in production.

**Comment by aneesh-neelam** [comment]
I'm not, I think [express-mongo-db](https://github.com/floatdrop/express-mongo-db) using it internally.

**Comment by aneesh-neelam** [comment]
@floatdrop: Are you telling me that [express-mongo-db](https://github.com/floatdrop/express-mongo-db) cannot be used in production?

**Comment by floatdrop** [comment]
@aneesh-neelam express-mongo-db does not have dependencies on `connect` inside - https://github.com/floatdrop/express-mongo-db/blob/master/package.json#L14-L17

**Comment by aneesh-neelam** [comment]
@floatdrop: I am so sorry, my mistake.

**Comment by govo** [comment]
So, who's using it?

**Comment by wahengchang** [comment]
same problem, does anyone got a solution ?

**Comment by KhalilKhalaf** [comment]
Ok looks like we can use some properties that can control this behavior: `interval`, `maxAge`, `cookie`, `saveUninitialized`, `resave` .. etc

More can be found here: [MongoDB fix: connection.session() MemoryStore is not designed for a production environment](https://digitalrizzle.wordpress.com/2013/04/26/mongodb-fix-connection-session-memorystore-is-not-designed-for-a-production-environment/)

Also that there are some hacks around this error, for example:

- Handle the error instead of crashing: https://stackoverflow.com/a/44884800/5890227

- use cookie-session instead of express-session: https://stackoverflow.com/a/37022764/5890227

- And/Or to force-clean all sessions in a custom function on our own: https://stackoverflow.com/a/10761522/5890227

I had same issue and did a quick research which is worth sharing. Hope it helps!
